### ISSUE TITLE
다 보인다고

### ISSUE THREAD

**Issue by jeongjiwoo0522** [AI-Meeting/XD-Backend#32]
https://github.com/AI-Meeting/XD-Backend/blob/db1b52991609c45a6d347d7f173e143d501b7864/src/ormconfig.json#L1-L13

이 자슥이 커밋 한번만 하면 되는줄 아나 
* 이 파일 들어간 커밋 다 지우거나 
* 레포를 지우거나 
* RDS 지우거나 
아무 일 없을 시 관리자가 직접 RDS, EC2 날려드립니다

**Comment by silverbeen** [comment]
ㄷㄷㄷ 바꿀 예정입니다요..
